spring.application.name=farmconnect-backend

spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:32941/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ZvckJHYoZyqNiT1kZylfvNjgjtdqIQjQ

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=30000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phanipanja25@gmail.com
spring.mail.password=qiihyqwftwlpwwhq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com